-- POPULANDO TABELAS --

INSERT INTO TB_USUARIO VALUES
	(null, 'admin', 'ESCRITA', '123456'),
	(null, 'comum', 'LEITURA', '123456');
	
INSERT INTO TB_TIPO_TELEFONE VALUES
	(null, 'RESIDENCIAL'),
	(null, 'COMERCIAL'),
	(null, 'CELULAR');
	
INSERT INTO TB_CLIENTE (ID_CLIENTE, CPF, NOME) 
	VALUES (NULL, 00011122233, 'Cliente de Teste');
INSERT INTO TB_CLIENTE (ID_CLIENTE, CPF, NOME) 
	VALUES (NULL, 33311144477, 'Cliente de Teste dois');
		
INSERT INTO TB_ENDERECO (ID_ENDERECO, BAIRRO, CEP, CIDADE, COMPLEMENTO, LOGRADOURO, UF) 
	VALUES (NULL, 'Samambaia Sul', '72307300', 'Brasília', NULL, 'QR 301 CONJUNTO 10 CASA X', 'DF');
INSERT INTO TB_ENDERECO (ID_ENDERECO, BAIRRO, CEP, CIDADE, COMPLEMENTO, LOGRADOURO, UF) 
	VALUES (NULL, 'Samambaia Sul', '72000000', 'Santo Antônio do Descoberto', NULL, 'PARQUE ANA BEATRIZ II', 'GO');


INSERT INTO CLIENTE_ENDERECO (ID_CLIENTE, ID_ENDERECO) 
	VALUES (1, 1);
INSERT INTO CLIENTE_ENDERECO (ID_CLIENTE, ID_ENDERECO) 
	VALUES (2, 2);

INSERT INTO TB_TELEFONE (ID_TELEFONE, ID_CLIENTE, NUMERO, ID_TIPO_TELEFONE) 
	VALUES (NULL, 1, 61985851263, 3);
INSERT INTO TB_TELEFONE (ID_TELEFONE, ID_CLIENTE, NUMERO, ID_TIPO_TELEFONE) 
	VALUES (NULL, 1, 61985851263, 3);
INSERT INTO TB_TELEFONE (ID_TELEFONE, ID_CLIENTE, NUMERO, ID_TIPO_TELEFONE) 
	VALUES (NULL, 2, 61852396667, 3);
INSERT INTO TB_TELEFONE (ID_TELEFONE, ID_CLIENTE, NUMERO, ID_TIPO_TELEFONE) 
	VALUES (NULL, 2, 6130529477, 1);

INSERT INTO TB_EMAIL (ID_EMAIL, ID_CLIENTE, EMAIL) 
	VALUES (NULL, 1, 'teste@email.com');
INSERT INTO TB_EMAIL (ID_EMAIL, ID_CLIENTE, EMAIL) 
	VALUES (NULL, 2, 'teste@email.com');
INSERT INTO TB_EMAIL (ID_EMAIL, ID_CLIENTE, EMAIL) 
	VALUES (NULL, 1, 'fulano@email.com');
INSERT INTO TB_EMAIL (ID_EMAIL, ID_CLIENTE, EMAIL) 
	VALUES (NULL, 2, 'fulano@email.com');
	